### ISSUE TITLE
SGN weight

### ISSUE THREAD

**Issue by aidevveloper** [KMU-KIWI/fast_action#2]
Hi @seonbin-kim 
Nice work. Thank You for sharing code.
Can you share sgn.onnx as well? Or tell me how to find it?

**Comment by seonbin-kim** [comment]
Hi @Harry-KIT,
Thank you for your attention.
You can download "sgn.onnx" [Here](https://www.dropbox.com/scl/fi/x6ui67c8s5my231kwh982/sgn.onnx?rlkey=g24sa5ka73d51715lrnqhbaml&st=7iyyd8nl&dl=0).

Note that, this repository was for testing two methods.
1. Semantics-Guided Neural Networks for Efficient Skeleton-Based Human Action Recognition, CVPR 2020.
2. Lightweight Semantic-Guided Neural Networks Based on Single Head Attention for Action Recognition, Sensors 2022.

If the problem occurs, please leave a comment again.

**Comment by aidevveloper** [comment]
Hi @seonbin-kim. I appreciate that.
One more thing again if you don't mind. Can you share yolov7-w6-pose.onnx too?

**Comment by seonbin-kim** [comment]
@Harry-KIT
I uploaded it [here](https://www.dropbox.com/scl/fi/3s6zpqe4rgrcmr3vufttc/yolov7-w6-pose.onnx?rlkey=7dx70ie2t0cb50nburlchz1vf&st=q7ipcgbl&dl=0).
We exported .onnx file from [YOLOv7 official repository](https://github.com/WongKinYiu/yolov7). You can check the original .pt file in the repository.

**Comment by aidevveloper** [comment]
Thank you very much @seonbin-kim

**Comment by seonbin-kim** [comment]
I close this issue. If you have more questions, please send me an email. The email address is sbkim@stu.kmu.ac.kr.
Thank you.
